name = 'dark'

# Color configuration
[colors]
black = "0"
red = "1"
green = "2"
yellow = "3"
blue = "4"
magenta = "5"
cyan = "6"
white = "7"
bright_black = "8"
bright_red = "9"
bright_green = "10"
bright_yellow = "11"
bright_blue = "12"
bright_magenta = "13"
bright_cyan = "14"
bright_white = "15"

gray = "248"

background = ""
overlay0 = "235"
overlay1 = "234"

text = "7"
subtext = "8"

primary = "6"
primary_selected = "14"

# Icon configuration
[icons]
root_dir = { icon = 0xef81, style = { foreground = '$red' } }
dir = { icon = 0xf024b }
open_dir = { icon = 0xf0770 }
file = { icon = 0xea7b }

error = { icon = 0xea87, style = { foreground = '$red' } }
warning = { icon = 0xf071, style = { foreground = '$yellow' } }
info = { icon = 0xf05a, style = { foreground = '$green' } }
hint = { icon = 0xf06e8, style = { foreground = '$cyan' } }

unknown_type = { icon = 0xeb63 }

# File Icon configuration
[icons.files]
"go" = { icon = 0xe627, style = { foreground = '$bright_cyan' } }
"go-mod" = { icon = 0xe627, style = { foreground = '$bright_cyan' }  }
"go-sum" = { icon = 0xe627, style = { foreground = '$bright_cyan' }  }
"go-work" = { icon = 0xe627, style = { foreground = '$bright_cyan' }  }
"go-template" = { icon = 0xe627, style = { foreground = '$bright_cyan' }  }
"templ" = { icon = 0xe627, style = { foreground = '$bright_cyan' }  }
"toml" = { icon = 0xe6b2, style = { foreground = '$bright_red' } }
"query" = { icon = 0xe21c }
"markdown" = { icon = 0xf0354 }
"comment" = { icon = 0xf075 }
"json" = { icon = 0xe60b }
"jsonc" = { icon = 0xe60b }
"json5" = { icon = 0xe60b }
"yaml" = { icon = 0xf0b20 }
"gitignore" = { icon = 0xf05e }
"git-commit" = { icon = 0xf05e }
"git-config" = { icon = 0xf05e }
"git-rebase" = { icon = 0xf05e }
"gitattributes" = { icon = 0xf05e }
"hyprlang" = { icon = 0xf359 }
"bash" = { icon = 0xf1183 }
"css" = { icon = 0xe749 }
"scss" = { icon = 0xe749 }
"dockerfile" = { icon = 0xf0868 }
"html" = { icon = 0xf031d }
"http" = { icon = 0xe749 }
"java" = { icon = 0xf0b37 }
"kotlin" = { icon = 0xf1219 }
"nix" = { icon = 0xf1105 }
"passwd" = { icon = 0xf4fc }
"properties" = { icon = 0xeb65 }
"regex" = { icon = 0xf0451 }
"sql" = { icon = 0xf01bc }
"sqlite" = { icon = 0xf01bc }
"sshd-config" = { icon = 0xf08c0 }
"xml" = { icon = 0xf05c0 }
"python" = { icon = 0xf0320 }
"requirements" = { icon = 0xf0320 }
"javascript" = { icon = 0xf031e }

# Type Icon configuration
[icons.types]
"text" = { icon = 0xeb8d, style = { foreground = '$bright_green' } }
"method" = { icon = 0xea8c, style = { foreground = '$bright_cyan' } }
"function" = { icon = 0xf0295, style = { foreground = '$bright_cyan' } }
"constructor" = { icon = 0xf423, style = { foreground = '$bright_cyan' } }
"field" = { icon = 0xeb5f, style = { foreground = '$bright_red' } }
"variable" = { icon = 0xea88, style = { foreground = '$white' } }
"class" = { icon = 0xeb5b, style = { foreground = '$bright_magenta' } }
"interface" = { icon = 0xeb61, style = { foreground = '$bright_magenta' } }
"module" = { icon = 0xea8b, style = { foreground = '$bright_magenta' } }
"property" = { icon = 0xeb65, style = { foreground = '$bright_red' } }
"unit" = { icon = 0xe21f, style = { foreground = '$white' } }
"value" = { icon = 0xea90, style = { foreground = '$yellow' } }
"enum" = { icon = 0xea95, style = { foreground = '$bright_magenta' } }
"keyword" = { icon = 0xeb62, style = { foreground = '$bright_magenta' } }
"snippet" = { icon = 0xeb66, style = { foreground = '$white' } }
"color" = { icon = 0xeb5c, style = { foreground = '$bright_white' } }
"file" = { icon = 0xea7b, style = { foreground = '$red' } }
"reference" = { icon = 0xf481, style = { foreground = '$red' } }
"folder" = { icon = 0xf024b, style = { foreground = '$red' } }
"enum_member" = { icon = 0xeb5e, style = { foreground = '$red' } }
"constant" = { icon = 0xeb5d, style = { foreground = '$red' } }
"struct" = { icon = 0xf1b3, style = { foreground = '$bright_magenta' } }
"event" = { icon = 0xea86, style = { foreground = '$bright_yellow' } }
"operator" = { icon = 0xeb64, style = { foreground = '$white' } }
"type_parameter" = { icon = 0xea92, style = { foreground = '$bright_yellow' } }

# UI Style configuration
[ui]
text = { foreground = '$text' }
subtext = { foreground = '$subtext' }

# App Bar Style configuration
[ui.app_bar]
style = { foreground = '$primary', reverse = true }
title = { foreground = '$primary', reverse = true }

# App Bar File Style configuration
[ui.app_bar.files]
style = { }
file = { foreground = '$primary_selected', reverse = true }
selected_file = { foreground = '$primary_selected', reverse = true }

# Code Bar Style configuration
[ui.code_bar]
style = { foreground = '$primary', reverse = true }

# General Menu Style configuration
[ui.menu]
style = { border_foreground = '$primary' }
title = { foreground = '$primary', reverse = true }
content = { foreground = '$text' }

entry = { foreground = '$text' }
selected_entry = { foreground = '$primary_selected', reverse = true }
selected_entry_unfocused = { foreground = '$primary', reverse = true }

# Basic Overlay Style configuration
[ui.overlay]
style = { background = '$surface0' }

# File Tree Style configuration
[ui.file_tree]
style = { foreground = '$text' }
empty = { foreground = '$subtext' }
entry = { foreground = '$text' }
selected_entry = { foreground = '$primary_selected', reverse = true }
selected_entry_unfocused = { foreground = '$primary', reverse = true }

# The Main Editor Style configuration
[ui.file_view]
style = { background = '$base', foreground = '$text' }
empty = { foreground = '$subtext' }
border = { border_foreground = '$primary' }

line = { }
line_prefix = { foreground = '$gray' }
line_char = { }

current_line = { background = '$overlay0' }
current_line_prefix = { background = '$overlay0' }
current_line_char = { background = '$overlay0' }

selection = { reverse = true }
inlay_hint = { foreground = '$subtext', background = '$overlay0', italic = true, bold = true }

# File Picker Style configuration
[ui.file_picker]
cursor = { foreground = '$primary' }
disabled_cursor = { foreground = '$subtext' }

selected = { foreground = '$primary_selected', reverse = true }
disabled_selected = { foreground = '$subtext' }

symlink = { foreground = '$cyan' }
directory = { foreground = '$green' }
empty_directory = { foreground = '$subtext' }

file = { foreground = '$text' }
disabled_file = { foreground = '$subtext' }
file_size = { foreground = '$subtext' }

permission = { foreground = '$yellow' }

# Text Input Style configuration
[ui.text_input]
prompt_char = '$ '
echo_char = '*'
prompt = { foreground = '$primary' }
focused_prompt = { foreground = '$primary_selected' }
text = { foreground = '$text' }
placeholder = { foreground = '$subtext' }

# Cursor Style configuration
[ui.cursor]
block = { foreground = '$red', reverse = true }
underline = { underline = true, underline_color = '$red' }

# Diagnostic Style configuration
[diagnostic]
error = { foreground = '$red', bold = true }
error_char = { curly_underline = true, underline_color = '$red' }

warning = { foreground = '$yellow', bold = true }
warning_char = { curly_underline = true, underline_color = '$yellow' }

info = { foreground = '$green', bold = true }
info_char = { curly_underline = true, underline_color = '$green' }

hint = { foreground = '$cyan', bold = true }
hint_char = { curly_underline = true, underline_color = '$cyan' }

deprecated = { foreground = '$gray', italic = true }
deprecated_char = { foreground = '$gray', strikethrough = true }

unnecessary = { foreground = '$red', italic = true }
unnecessary_char = { curly_underline = true, underline_color = '$red' }

# Code styles
[code_styles]
"tag" = { foreground = '$bright_red' }
"attribute" = { foreground = '$yellow', italic = true }
"property" = { foreground = '$bright_red' }
"label" = { foreground = '$bright_white', bold = true }

"comment" = { foreground = '8', italic = true }
"comment.error" = { foreground = '$red', bold = true }
"comment.warning" = { foreground = '$yellow', bold = true }
"comment.note" = { foreground = '$green', bold = true }
"comment.todo" = { foreground = '$bright_white', bold = true }

"variable" = { foreground = '$white' }
"variable.builtin" = { foreground = '$bright_cyan' }
"variable.parameter" = { foreground = '$yellow' }
"variable.other" = { foreground = '$red' }
"variable.other.member" = { foreground = '$white' }

"constant" = { foreground = '$yellow' }
"constant.numeric" = { foreground = '$yellow' }
"constant.numeric.integer" = { foreground = '$yellow' }
"constant.numeric.float" = { foreground = '$yellow' }
"constant.builtin" = { foreground = '$bright_red' }
"constant.builtin.boolean" = { foreground = '$yellow' }
"constant.character.escape" = { foreground = '$cyan', bold = true }
"constant.other.placeholder" = { foreground = '$cyan', bold = true }

"function" = { foreground = '$bright_cyan' }
"function.builtin" = { foreground = '$bright_cyan' }
"function.macro" = { foreground = '$bright_cyan' }
"constructor" = { foreground = '$bright_cyan' }
"keyword" = { foreground = '$bright_magenta', italic = true }
"keyword.directive" = { foreground = '$bright_magenta', italic = true }
"section" = { foreground = '$bright_magenta' }

"punctuation.delimiter" = { foreground = '$white' }
"punctuation.special" = { foreground = '$bright_magenta' }
"punctuation.bracket" = { foreground = '$white' }

"operator" = { foreground = '$white' }
"special" = { foreground = '$bright_cyan' }
"string" = { foreground = '$bright_green', bold = true }
"string.special" = { foreground = '$yellow' }
"string.special.path" = { foreground = '$bright_green', bold = true }
"string.special.url" = { foreground = '$blue' }
"type" = { foreground = '$bright_yellow', bold = true }

"markup.heading" = { foreground = '$cyan' }
"markup.heading.marker" = { foreground = '$bright_magenta' }
"markup.raw" = { foreground = '$bright_green' }
# reset highlight for block code to allow injection of language specific styles
"markup.raw.block" = { foreground = '$white' }
"markup.list" = { foreground = '$bright_magenta' }
"markup.quote" = { foreground = '$bright_green' }
"markup.link.url" = { foreground = '$bright_cyan', underline = true }
"markup.link.text" = { foreground = '$bright_magenta', underline = true }
"markup.bold" = { bold = true }
"markup.italic" = { italic = true }
"markup.underline" = { underline = true }
"markup.strikethrough" = { strikethrough = true }

"diff.plus" = { foreground = '$bright_green' }
"diff.delta" = { foreground = '$bright_yellow' }
"diff.minus" = { foreground = '$bright_red' }

# Language specific styles
"property.toml" = { foreground = '$bright_magenta', italic = true }
