name = 'dark-simple'

# Color configuration
[colors]
primary_color = '6'
primary_selected_color = '14'
primary_text_color = '15'
secondary_text_color = '248'
disabled_text_color = '8'
background_color = ''
secondary_background_color = '235'
error_color = '1'
warning_color = '3'
information_color = '2'
hint_color = '6'
cursor_color = '9'
disabled_cursor_color = '1'

[icons]
root_dir = 0xef81
dir = 0xf024b
open_dir = 0xf0770
file = 0xea7b

error = 0xea87
warning = 0xf071
information = 0xf05a
hint = 0xf06e8

[styles]
[styles.diagnostics]
error = { underline = true }
warning = { underline = true }
information = { underline = true }
hint = { underline = true }

# Code style configuration
[code]
"tag" = { foreground = '9' }
"attribute" = { foreground = '3' }
"property" = { foreground = '9' }
"label" = { foreground = '11' }

"comment" = { foreground = '8' }
"comment.error" = { foreground = '1', bold = true }
"comment.warning" = { foreground = '3', bold = true }
"comment.note" = { foreground = '2', bold = true }
"comment.todo" = { foreground = '15', bold = true }

"constant" = { foreground = '11' }
"constant.numeric" = { foreground = '3' }
"constant.builtin" = { foreground = '9' }
"constant.builtin.boolean" = { foreground = '3' }
"constant.character.escape" = { foreground = '10' }

"function" = { foreground = '14' }
"function.builtin" = { foreground = '14' }
"function.macro" = { foreground = '14' }
"constructor" = { foreground = '14' }
"keyword" = { foreground = '13' }
"section" = { foreground = '13' }

#"punctuation.delimiter" = { foreground = '11' }
"punctuation.special" = { foreground = '13' }
#"punctuation.bracket" = { foreground = '11' }

"operator" = { }
"keyword.operator" = { }
"special" = { foreground = '14' }
"string" = { foreground = '10', bold = true }
"string.escape" = { foreground = '14' }
"string.special" = { foreground = '3' }
"string.special.url" = { foreground = '4' }
"number" = { foreground = '3' }
"boolean" = { foreground = '3' }
"type" = { foreground = '11' }

"variable.builtin" = { foreground = '14' }
"variable.parameter" = { foreground = '9' }
"variable.other.member" = { foreground = '9' }

"markup.heading" = { foreground = '6' }
"markup.raw" = { foreground = '10' }
# reset highlight for block code to allow injection of language specific styles
"markup.raw.block" = { }
"markup.list" = { foreground = '13' }
"markup.quote" = { foreground = '10' }
"markup.link.url" = { foreground = '14', underline = true }
"markup.link.text" = { foreground = '13' }
"markup.bold" = { bold = true }
"markup.italic" = { italic = true }
"markup.underline" = { underline = true }
"markup.strikethrough" = { strikethrough = true }

"diff.plus" = { foreground = '10' }
"diff.delta" = { foreground = '11' }
"diff.minus" = { foreground = '9' }