name = 'dark'

# Color configuration
[colors]
primary_color = '6'
primary_selected_color = '14'
primary_text_color = '7'
secondary_text_color = '248'
disabled_text_color = '8'
background_color = ''
secondary_background_color = '235'
cursor_color = '9'
disabled_cursor_color = '1'

[icons]
root_dir = 0xef81
dir = 0xf024b
open_dir = 0xf0770
file = 0xea7b

error = 0xea87
warning = 0xf071
information = 0xf05a
hint = 0xf06e8

[icons.files]
"go" = 0xe627
"go-mod" = 0xe627
"go-sum" = 0xe627
"go-work" = 0xe627
"go-template" = 0xe627
"templ" = 0xe627
"toml" = 0xe6b2
"query" = 0xe21c
"markdown" = 0xf0354
"comment" = 0xf075
"json" = 0xe60b
"jsonc" = 0xe60b
"json5" = 0xe60b
"yaml" = 0xf0b20
"gitignore" = 0xf05e
"git-commit" = 0xf05e
"git-config" = 0xf05e
"git-rebase" = 0xf05e
"gitattributes" = 0xf05e
"hyprlang" = 0xf359
"bash" = 0xf1183
"css" = 0xe749
"scss" = 0xe749
"dockerfile" = 0xf0868
"html" = 0xf031d
"http" = 0xe749
"java" = 0xf0b37
"kotlin" = 0xf1219
"nix" = 0xf1105
"passwd" = 0xf4fc
"properties" = 0xeb65
"regex" = 0xf0451
"sql" = 0xf01bc
"sqlite" = 0xf01bc
"sshd-config" = 0xf08c0
"xml" = 0xf05c0
"python" = 0xf0320
"requirements" = 0xf0320
"javascript" = 0xf031e

unknown_type = 0xeb63

[icons.types]
"text" = { icon = 0xeb8d, style = { foreground = '10' } }
"method" = { icon = 0xea8c, style = { foreground = '14' } }
"function" = { icon = 0xf0295, style = { foreground = '14' } }
"constructor" = { icon = 0xf423, style = { foreground = '14' } }
"field" = { icon = 0xeb5f, style = { foreground = '9' } }
"variable" = { icon = 0xea88, style = { foreground = '7' } }
"class" = { icon = 0xeb5b, style = { foreground = '13' } }
"interface" = { icon = 0xeb61, style = { foreground = '13' } }
"module" = { icon = 0xea8b, style = { foreground = '13' } }
"property" = { icon = 0xeb65, style = { foreground = '9' } }
"unit" = { icon = 0xe21f, style = { foreground = '7' } }
"value" = { icon = 0xea90, style = { foreground = '3' } }
"enum" = { icon = 0xea95, style = { foreground = '13' } }
"keyword" = { icon = 0xeb62, style = { foreground = '13' } }
"snippet" = { icon = 0xeb66, style = { foreground = '7' } }
"color" = { icon = 0xeb5c, style = { foreground = '15' } }
"file" = { icon = 0xea7b, style = { foreground = '1' } }
"reference" = { icon = 0xf481, style = { foreground = '1' } }
"folder" = { icon = 0xf024b, style = { foreground = '1' } }
"enum_member" = { icon = 0xeb5e, style = { foreground = '1' } }
"constant" = { icon = 0xeb5d, style = { foreground = '1' } }
"struct" = { icon = 0xf1b3, style = { foreground = '13' } }
"event" = { icon = 0xea86, style = { foreground = '11' } }
"operator" = { icon = 0xeb64, style = { foreground = '7' } }
"type_parameter" = { icon = 0xea92, style = { foreground = '11' } }

# Style configuration
[styles]
"error" = { foreground = '1', bold = true }
"warning" = { foreground = '3', bold = true }
"information" = { foreground = '2', bold = true }
"hint" = { foreground = '248', bold = true }
"trace" = { foreground = '15', bold = true }

# Code styles
"error.inline" = { underline = true, underline_style = 'curly', underline_color = '1' }
"warning.inline" = { underline = true, underline_style = 'curly', underline_color = '3' }
"information.inline" = { underline = true, underline_style = 'curly', underline_color = '2' }
"hint.inline" = { underline = true, underline_style = 'curly', underline_color = '248' }

"tag" = { foreground = '9' }
"attribute" = { foreground = '3', italic = true }
"property" = { foreground = '9' }
"label" = { foreground = '15', bold = true }

"comment" = { foreground = '8', italic = true }
"comment.error" = { foreground = '1', bold = true }
"comment.warning" = { foreground = '3', bold = true }
"comment.note" = { foreground = '2', bold = true }
"comment.todo" = { foreground = '15', bold = true }

"variable" = { foreground = '7' }
"variable.builtin" = { foreground = '14' }
"variable.parameter" = { foreground = '3' }
"variable.other" = { foreground = '1' }
"variable.other.member" = { foreground = '7' }

"constant" = { foreground = '3' }
"constant.numeric" = { foreground = '3' }
"constant.numeric.integer" = { foreground = '3' }
"constant.numeric.float" = { foreground = '3' }
"constant.builtin" = { foreground = '9' }
"constant.builtin.boolean" = { foreground = '3' }
"constant.character.escape" = { foreground = '6', bold = true }
"constant.other.placeholder" = { foreground = '6', bold = true }

"function" = { foreground = '14' }
"function.builtin" = { foreground = '14' }
"function.macro" = { foreground = '14' }
"constructor" = { foreground = '14' }
"keyword" = { foreground = '13', italic = true }
"keyword.directive" = { foreground = '13', italic = true }
"section" = { foreground = '13' }

"punctuation.delimiter" = { foreground = '7' }
"punctuation.special" = { foreground = '13' }
"punctuation.bracket" = { foreground = '7' }

"operator" = { foreground = '7' }
"special" = { foreground = '14' }
"string" = { foreground = '10', bold = true }
"string.special" = { foreground = '3' }
"string.special.path" = { foreground = '10', bold = true }
"string.special.url" = { foreground = '4' }
"type" = { foreground = '11', bold = true }

"markup.heading" = { foreground = '6' }
"markup.heading.marker" = { foreground = '13' }
"markup.raw" = { foreground = '10' }
# reset highlight for block code to allow injection of language specific styles
"markup.raw.block" = { foreground = '7' }
"markup.list" = { foreground = '13' }
"markup.quote" = { foreground = '10' }
"markup.link.url" = { foreground = '14', underline = true }
"markup.link.text" = { foreground = '13', underline = true }
"markup.bold" = { bold = true }
"markup.italic" = { italic = true }
"markup.underline" = { underline = true }
"markup.strikethrough" = { strikethrough = true }

"diff.plus" = { foreground = '10' }
"diff.delta" = { foreground = '11' }
"diff.minus" = { foreground = '9' }

# Language specific styles
"property.toml" = { foreground = '13', italic = true }
