# Key bindings configuration

quit = 'ctrl+q'
help = 'ctrl+h'
ok = 'enter'
cancel = 'esc'
left = 'left'
right = 'right'
up = 'up'
down = 'down'
run = 'ctrl+k'
terminal = 'ctrl+t'
key_mapper = 'f4'

# Editor key bindings configuration
[editor]
open_file = 'ctrl+o'
open_folder = 'alt+o'
save_file = 'ctrl+s'
close_file = 'ctrl+w'
new_file = 'ctrl+n'
rename_file = 'ctrl+r'
delete_file = 'ctrl+g'
search = 'ctrl+f'
open_outline = 'alt+7'
toggle_file_tree = 'ctrl+b'
focus_file_tree = 'alt+b'
next_file = 'alt+right'
prev_file = 'alt+left'
autocomplete = 'ctrl+@'
next_completion = 'down'
prev_completion = 'up'
apply_completion = 'enter'
refresh_syntax_highlight = 'f1'
toggle_tree_sitter_debug = 'f2'
debug_tree_sitter_nodes = 'f3'
show_current_diagnostic = 'ctrl+j'
show_definitions = 'alt+.'
character_left = 'left'
character_right = 'right'
word_left = 'ctrl+left'
word_right = 'ctrl+right'
line_up = 'up'
line_down = 'down'
word_up = 'ctrl+up'
word_down = 'ctrl+down'
page_up = 'pgup'
page_down = 'pgdown'
line_start = 'home'
line_end = 'end'
file_start = 'ctrl+home'
file_end = 'ctrl+end'
select_left = 'shift+left'
select_right = 'shift+right'
select_up = 'shift+up'
select_down = 'shift+down'
select_all = 'ctrl+a'
cut = 'ctrl+x'
copy = 'ctrl+c'
paste = 'ctrl+v'
undo = 'ctrl+z'
redo = 'ctrl+y'
tab = 'tab'
remove_tab = 'shift+tab'
newline = 'enter'
delete_left = 'backspace'
delete_right = 'delete'
delete_word_left = 'ctrl+backspace'
delete_word_right = 'ctrl+delete'
duplicate_line = 'ctrl+d'
delete_line = 'alt+backspace'
toggle_comment = 'ctrl+_'
debug = 'f12'

# File tree key bindings configuration
[editor.file_tree]
select_prev = 'up'
select_next = 'down'
expand_width = 'ctrl+right'
shrink_width = 'ctrl+left'
open = 'enter'
refresh = 'ctrl+r'

# Search bar key bindings configuration
[editor.search_bar]
select_prev = 'up'
select_next = 'down'
select_result = 'enter'
close = 'esc'

# File picker key bindings configuration
[file_picker]
go_to_top = 'home'
go_to_end = 'end'
up = 'up'
down = 'down'
page_up = 'pgup'
page_down = 'pgdown'
back = 'left'
open = 'right'
select = 'enter'
