# Key bindings configuration

quit = 'ctrl+q'
help = 'ctrl+h'
ok = 'enter'
cancel = 'esc'
left = 'left'
right = 'right'
up = 'up'
down = 'down'
run = 'ctrl+k'
terminal = 'ctrl+t'
key_mapper = 'f4'
debug = 'f12'

# Editor key bindings configuration
[editor]
toggle_file_tree = 'ctrl+b'
focus_file_tree = 'alt+b'
search = 'ctrl+f'
open_outline = 'alt+7'

refresh_syntax_highlight = 'f1'
toggle_tree_sitter_debug = 'f2'
debug_tree_sitter_nodes = 'f3'

[editor.file]
open = 'ctrl+o'
open_folder = 'alt+o'
close = 'ctrl+w'

new = 'ctrl+n'
rename = 'f5'
save = 'ctrl+s'
delete = 'f6'

next = 'alt+right'
prev = 'alt+left'

[editor.navigation]
character_left = 'left'
character_right = 'right'
word_left = 'ctrl+left'
word_right = 'ctrl+right'

line_up = 'up'
line_down = 'down'
word_up = 'ctrl+up'
word_down = 'ctrl+down'
page_up = 'pgup'
page_down = 'pgdown'

line_start = 'home'
line_end = 'end'
file_start = 'ctrl+home'
file_end = 'ctrl+end'

go_to = 'ctrl+g'

[editor.selection]
select_left = 'shift+left'
select_right = 'shift+right'
select_up = 'shift+up'
select_down = 'shift+down'

select_all = 'ctrl+a'

[editor.edit]
tab = 'tab'
remove_tab = 'shift+tab'

paste = 'ctrl+v'
copy = 'ctrl+c'
cut = 'ctrl+x'

undo = 'ctrl+z'
redo = 'ctrl+y'

delete_left = 'backspace'
delete_right = 'delete'
delete_word_left = 'ctrl+backspace'
delete_word_right = 'ctrl+delete'

duplicate_line = 'ctrl+d'
delete_line = 'alt+backspace'

toggle_comment = 'ctrl+_'

[editor.code]
show_declaration = 'alt+,'
show_definitions = 'alt+.'
show_type_definition = 'alt+>'
show_implementation = 'alt+<'
show_references = 'alt+;'

# Autocomplete key bindings configuration
[editor.autocomplete]
show = 'ctrl+space'
next = 'down'
prev = 'up'
apply = 'enter'

# Diagnostic key bindings configuration
[editor.diagnostic]
show = 'ctrl+j'
next = 'down'
prev = 'up'

# File tree key bindings configuration
[editor.file_tree]
select_prev = 'up'
select_next = 'down'
expand_width = 'ctrl+right'
shrink_width = 'ctrl+left'
open = 'enter'
refresh = 'ctrl+r'

# Search bar key bindings configuration
[editor.search_bar]
select_prev = 'up'
select_next = 'down'
select_result = 'enter'
close = 'esc'

# File picker key bindings configuration
[file_picker]
go_to_top = 'home'
go_to_end = 'end'
up = 'up'
down = 'down'
page_up = 'pgup'
page_down = 'pgdown'
back = 'left'
open = 'right'
select = 'enter'
