# Languages configuration
# Language icons can be found at https://www.nerdfonts.com/cheat-sheet, make sure you have a Nerd Font installed

[go]
icon = 0xe627
alt_names = ['golang']
mime_types = ['text/x-gosrc']
file_types = ['.go']
files = []
line_comment_tokens = ['//']
block_comment_tokens = [{ start = '/*', end = '*/' }]
auto_pairs = [{ open = '(', close = ')' }, { open = '{', close = '}' }, { open = '[', close = ']' }, { open = '"', close = '"' }, { open = "'", close = "'" }, { open = '`', close = '`' }]
grammar = { symbol_name = 'go', path = '/usr/lib/libtree-sitter-go.so' }

[go-mod]
icon = 0xe627
alt_names = ['go.mod']
mime_types = []
file_types = []
files = ['go.mod']
line_comment_tokens = ['//']
block_comment_tokens = []
auto_pairs = []
grammar = { symbol_name = 'gomod', path = '/usr/lib/libtree-sitter-gomod.so' }

[go-sum]
icon = 0xe627
alt_names = ['go.sum', 'go.work.sum']
mime_types = []
file_types = []
files = ['go.sum', 'go.work.sum']
line_comment_tokens = ['//']
block_comment_tokens = []
auto_pairs = []
grammar = { symbol_name = 'gosum', path = '/usr/lib/libtree-sitter-gosum.so' }

[go-work]
icon = 0xe627
alt_names = ['go.work']
mime_types = []
file_types = []
files = ['go.work']
line_comment_tokens = ['//']
block_comment_tokens = []
auto_pairs = []
grammar = { symbol_name = 'gowork', path = '/usr/lib/libtree-sitter-gowork.so' }

[toml]
icon = 0xe6b2
alt_names = []
mime_types = []
file_types = ['.toml']
files = []
line_comment_tokens = ['#']
block_comment_tokens = []
auto_pairs = [{ open = '"', close = '"' }, { open = "'", close = "'" }]
grammar = { symbol_name = 'toml', path = '/usr/lib/libtree-sitter-toml.so' }

[query]
icon = 0xe21c
alt_names = ['tree sitter query']
mime_types = []
file_types = ['.scm']
files = []
line_comment_tokens = ['#']
block_comment_tokens = []
auto_pairs = [{ open = '"', close = '"' }, { open = '(', close = ')' }, { open = '[', close = ']' }]
grammar = { symbol_name = 'query', path = '/usr/lib/libtree-sitter-query.so' }

[markdown]
icon = 0xf0354
alt_names = ['md']
mime_types = []
file_types = ['.md']
files = []
line_comment_tokens = []
block_comment_tokens = []
auto_pairs = []
#grammar = { symbol_name = 'markdown', path = '/usr/lib/libtree-sitter-markdown.so' }

[comment]
icon = 0xf075
alt_names = []
mime_types = []
file_types = []
files = []
line_comment_tokens = []
block_comment_tokens = []
auto_pairs = []
grammar = { symbol_name = 'comment', path = '/usr/lib/libtree-sitter-comment.so' }

[json]
icon = 0xe60b
alt_names = []
mime_types = []
file_types = ['.json']
files = []
line_comment_tokens = []
block_comment_tokens = []
auto_pairs = [{ open = '"', close = '"' }, { open = '{', close = '}' }, { open = '(', close = ')' }, { open = '[', close = ']' }]
grammar = { symbol_name = 'json', path = '/usr/lib/libtree-sitter-json.so' }

[json5]
icon = 0xe60b
alt_names = []
mime_types = []
file_types = ['.json5']
files = []
line_comment_tokens = ['//']
block_comment_tokens = []
auto_pairs = [{ open = '"', close = '"' }, { open = '{', close = '}' }, { open = '(', close = ')' }, { open = '[', close = ']' }]
grammar = { symbol_name = 'json5', path = '/usr/lib/libtree-sitter-json5.so' }

[yaml]
icon = 0xf0b20
alt_names = ['yml']
mime_types = []
file_types = ['.yaml', '.yml']
files = []
line_comment_tokens = ["#"]
block_comment_tokens = []
auto_pairs = []
grammar = { symbol_name = 'yaml', path = '/usr/lib/libtree-sitter-yaml.so' }

[gitignore]
icon = 0xf05e
alt_names = []
mime_types = []
file_types = ['.gitignore']
files = []
line_comment_tokens = []
block_comment_tokens = []
auto_pairs = []
grammar = { symbol_name = 'gitignore', path = '/usr/lib/libtree-sitter-gitignore.so' }

[git-commit]
icon = 0xf05e
alt_names = []
mime_types = []
file_types = []
files = ['COMMIT_EDITMSG']
line_comment_tokens = ['#']
block_comment_tokens = []
auto_pairs = []
grammar = { symbol_name = 'git_commit', path = '/usr/lib/libtree-sitter-git-commit.so' }
