# Language Server Protocol configuration
# For a list of available language servers, see: https://langserver.org/#implementations-server

use_servers = { only = ['gopls', 'golangci-lint', 'superhtml'], except = [] }

[language_servers.gopls]
command = 'gopls'
args = []
file_types = ['.go']
files = ['go.mod', 'go.sum', 'go.work', 'go.work.sum']
roots = ['go.mod', 'go.sum', 'go.work', 'go.work.sum']
features = ['inlay_hints', 'diagnostics', 'completion', 'go_to_definition']

[language_servers.gopls.config]
'ui.completion.usePlaceholders' = true
'ui.diagnostic.staticcheck' = true

[language_servers.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
compositeLiteralTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language_servers.golangci-lint]
command = 'golangci-lint-langserver'
args = ['-debug', '-severity', 'Hint']
file_types = ['.go']
files = []

[language_servers.golangci-lint.config]
command = ['golangci-lint', 'run', '--out-format', 'json', '--issues-exit-code=1']

[language_servers.yaml]
command = 'yaml-language-server'
args = ['--stdio']
file_types = ['.yaml', '.yml']
files = []

[language_servers.json]
command = 'vscode-json-languageserver'
args = ['--stdio']
file_types = ['.json', '.jsonc']
files = []

[language_servers.json.config]
provideFormatter = true
json = { validate = { enable = true } }

[language_servers.html]
command = 'vscode-html-language-server'
args = ['--stdio']
file_types = ['.html', '.htm']
files = []

[language_servers.superhtml]
command = 'superhtml'
args = ['lsp']
file_types = ['.html', '.htm']
files = []

[language_servers.toml]
command = 'taplo'
args = ['language_servers', 'stdio']
file_types = ['.toml']
files = []

[language_servers.ts-query]
command = 'ts_query_ls'
args = []
file_types = ['.scm']
files = []
roots = []
features = ['diagnostics']

[language_servers.ts-query.config.settings]
'parser_install_directories' = ['config/grammars']
'parser_aliases' = {}
'language_retrieval_patterns' = [ 'config/queries/([^/]+)/[^/]+\\.scm$' ]