# Language Server Protocol configuration
# For a list of available language servers, see: https://langserver.org/#implementations-server

[gopls]
command = 'gopls'
args = []
file_types = ['.go']
files = ['go.mod', 'go.sum', 'go.work', 'go.work.sum']

[gopls.config]
'ui.completion.usePlaceholders' = true
'ui.diagnostic.staticcheck' = true



[golangci-lint]
command = 'golangci-lint-langserver'
args = ['-debug', '-severity', 'Hint']
file_types = ['.go']
files = []

[golangci-lint.config]
command = ['golangci-lint', 'run', '--out-format', 'json', '--issues-exit-code=1']

#[yaml]
#command = 'yaml-language-server'
#args = ['--stdio']
#file_types = ['.yaml', '.yml']
#files = []

#[json]
#command = 'vscode-json-languageserver'
#args = ['--stdio']
#file_types = ['.json', '.jsonc']
#files = []

#[html]
#command = 'vscode-html-language-server'
#args = ['--stdio']
#file_types = ['.html', '.htm']
#files = []

#[toml]
#command = 'taplo'
#args = ['lsp', 'stdio']
#file_types = ['.toml']
#files = []
