# Language Server Protocol configuration
# For a list of available language servers, see: https://langserver.org/#implementations-server

[go]
command = 'gopls'
args = []
file_types = ['.go']
files = ['go.mod', 'go.sum', 'go.work', 'go.work.sum']

#[golangci-lint]
#command = 'golangci-lint-langserver'
#args = ['-debug', '-severity', 'Hint']
#config = { command = ['golangci-lint', 'run', '--out-format', 'json', '--issues-exit-code=1'] }
#file_types = ['.go']
#files = []
#
#[yaml]
#command = 'yaml-language-server'
#args = ['--stdio']
#file_types = ['.yaml', '.yml']
#files = []
#
#[json]
#command = 'vscode-json-languageserver'
#args = ['--stdio']
#file_types = ['.json', '.jsonc']
#files = []
#
#[html]
#command = 'vscode-html-language-server'
#args = ['--stdio']
#file_types = ['.html', '.htm']
#files = []
#
#[toml]
#command = 'taplo'
#args = ['lsp', 'stdio']
#file_types = ['.toml']
#files = []
